spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/TestDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:29092

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0

jwt:
  expiry-hour: 8
  expiry-day: 30
  secret-key: e10ccfd6a792ea78abd455182b7e16c17f4fb6a1f6aebeeee876794a164784a8